// The synthetic universe as the app holds it: fictional issuers and
// issues, generated by tyche-market (Rust, in a worker) from a seed and
// the Bank of Russia figures of the valuation date, and read here from
// the JSON the generator writes. Each issue's price was set by tyche-yield
// from the zero-coupon curve at its duration plus a spread for its rating
// and sector, so the yields the engine finds are where the generator put
// them. Nothing here is market data.
import type { Issue } from "@tyche/yield-twin";

export const RATINGS = ["AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-", "BB+", "BB", "BB-", "B+", "B"] as const;
export type Rating = (typeof RATINGS)[number];

export const PLACES = [
  "volga", "kama", "oka", "neva", "ob", "amur", "baikal", "ural",
  "don", "angara", "irtysh", "lena", "pechora", "onega", "kuban", "yenisei",
  "vyatka", "sura", "kolyma", "selenga", "tobol", "vetluga", "mezen", "khoper",
  "sviyaga", "ilmen", "ladoga", "seliger", "tavda", "chusovaya", "belaya", "shilka",
] as const;
export type Place = (typeof PLACES)[number];

export const SECTORS = ["government", "energy", "metals", "logistics", "retail", "telecom", "development", "agro", "leasing", "banking", "chemicals"] as const;
export type Sector = (typeof SECTORS)[number];

export type CouponKind = "fixed" | "key_rate" | "ruonia" | "linker";

export const OUTLOOKS = ["stable", "positive", "negative"] as const;
/** Where the fictional agency expects the issuer's rating to go. */
export type Outlook = (typeof OUTLOOKS)[number];

/** Who issued it: the synthetic treasury, or a fictional company named
 * after a place and its line of business. */
export type Issuer = { code: string; kind: "government" } | { code: string; kind: "corporate"; place: Place; sector: Exclude<Sector, "government"> };

export type Bond = {
  /** The ticker: Latin letters, digits and a hyphen, the same in every
   * language. */
  id: string;
  issuer: Issuer;
  /** On the synthetic scale. */
  rating: Rating;
  /** The issuer's rating outlook. */
  outlook: Outlook;
  coupon: {
    kind: CouponKind;
    /** Over the key rate or RUONIA, percent. */
    indexSpreadPct: number;
    /** A linker's face value over its original one. */
    indexRatio: number;
  };
  offer: { date: string; kind: "put" | "call" } | null;
  subordinated: boolean;
  qualifiedOnly: boolean;
  /** Bonds per lot. */
  lot: number;
  /** Price step, percent of face. */
  tickPct: number;
  /** The yield the generator priced it at (real for a linker), and its
   * modified duration then, years. */
  targetYield: number;
  duration: number;
  /** How the issue trades in the synthetic market. */
  liquidity: { rank: number; spreadBp: number; depth: number; tradesPerDay: number; morning: boolean; evening: boolean };
  /** What the engine takes. */
  issue: Issue;
};

/** The Bank of Russia figures a universe is generated for. */
export type MacroInputs = {
  valuationDate: string;
  keyRatePct: number;
  ruoniaPct: number;
  inflationPct: number;
  curve: { termsYears: number[]; yieldsPct: number[] };
};

export type Universe = { seed: number; inputs: MacroInputs; bonds: Bond[] };

type RawIssue = {
  ticker: string;
  segment: "government" | "corporate";
  issuer: string;
  place: string;
  sector: string;
  rating: string;
  outlook: string;
  coupon: Bond["coupon"];
  offer: Bond["offer"];
  subordinated: boolean;
  qualifiedOnly: boolean;
  lot: number;
  tickPct: number;
  targetYield: number;
  duration: number;
  liquidity: Bond["liquidity"];
  issue: Issue;
};

const isPlace = (x: string): x is Place => (PLACES as readonly string[]).includes(x);
const isSector = (x: string): x is Sector => (SECTORS as readonly string[]).includes(x);
const isRating = (x: string): x is Rating => (RATINGS as readonly string[]).includes(x);
const isOutlook = (x: string): x is Outlook => (OUTLOOKS as readonly string[]).includes(x);

/** Reads the generator's JSON. Throws on a place, sector, rating or outlook the
 * interface has no words for, so a generator change cannot show a blank. */
export function parseUniverse(json: string): Universe {
  const raw = JSON.parse(json) as { seed: number; inputs: MacroInputs; issues: RawIssue[] };
  const bonds = raw.issues.map((r): Bond => {
    if (!isRating(r.rating)) throw new Error(`${r.ticker}: unknown rating ${r.rating}`);
    if (!isOutlook(r.outlook)) throw new Error(`${r.ticker}: unknown outlook ${r.outlook}`);
    let issuer: Issuer;
    if (r.segment === "government") issuer = { code: r.issuer, kind: "government" };
    else {
      if (!isPlace(r.place) || !isSector(r.sector) || r.sector === "government") throw new Error(`${r.ticker}: unknown issuer ${r.place} ${r.sector}`);
      issuer = { code: r.issuer, kind: "corporate", place: r.place, sector: r.sector };
    }
    return {
      id: r.ticker,
      issuer,
      rating: r.rating,
      outlook: r.outlook,
      coupon: r.coupon,
      offer: r.offer,
      subordinated: r.subordinated,
      qualifiedOnly: r.qualifiedOnly,
      lot: r.lot,
      tickPct: r.tickPct,
      targetYield: r.targetYield,
      duration: r.duration,
      liquidity: r.liquidity,
      issue: r.issue,
    };
  });
  return { seed: raw.seed, inputs: raw.inputs, bonds };
}

/** Who may buy an issue, by tyche-market's rule for the synthetic
 * universe: anyone, a non-qualified investor after a passed test, or
 * qualified investors only. */
export type Access = "open" | "test" | "qualified";

/** Reads tyche-market's accessJson: each issue's access, by ticker. */
export function parseAccess(json: string): Map<string, Access> {
  const raw = JSON.parse(json) as { issues: { ticker: string; access: string }[] };
  const out = new Map<string, Access>();
  for (const i of raw.issues) {
    if (i.access !== "open" && i.access !== "test" && i.access !== "qualified") throw new Error(`${i.ticker}: unknown access ${i.access}`);
    out.set(i.ticker, i.access);
  }
  return out;
}

export function ratingIndex(r: Rating): number {
  return RATINGS.indexOf(r);
}

/** A floater, on the key rate or on RUONIA: the engine pays it as the key
 * rate plus a spread. */
export const isFloater = (b: Bond) => b.issue.couponType === "floater";
