// The synthetic universe the app shows, generated by tyche-market's
// WebAssembly build as the worker generates it: the same universe as the
// Rust crate's (one digest), from the same Bank of Russia figures, every
// issue priced so the engine finds its yield back, every kind the screen
// shows, and no real name among the ones the screen writes.
import { describe, expect, it } from "vitest";
import { derive_bond } from "@tyche/yield-twin";
import { strings } from "../i18n";
import { issuerName } from "../lib/names";
import { MACRO, MARKET, SEED, SNAPSHOT } from "./market";
import { parseUniverse, type Bond } from "./issues";
import { BONDS, dayJson, fallbackInputs, generate } from "./universe.testing";

/** The digest tests/synth.rs pins for the native build. */
const DIGEST = "f5adfa55cefab800";

describe("the synthetic universe", () => {
  it("is the native build's universe, bit for bit, and the same on every run", () => {
    // On the figures the crate's digests are pinned to.
    expect(generate(SEED, fallbackInputs()).digest).toBe(DIGEST);
    expect(generate()).toEqual(generate());
    expect(generate(SEED + 1).digest).not.toBe(generate().digest);
  });

  it("is generated from the Bank of Russia snapshot the build carries", () => {
    const l = SNAPSHOT.latest;
    expect(MACRO).toEqual({ valuationDate: l.date, keyRatePct: l.keyRatePct, ruoniaPct: l.ruoniaPct, inflationPct: l.inflationPct, curve: l.curve });
    expect(MARKET).toEqual({ valuationDate: MACRO.valuationDate, keyRatePct: MACRO.keyRatePct });
    expect(SNAPSHOT.terms).toBe("https://www.cbr.ru/user_agreement/");
    expect(SNAPSHOT.curve.calculatedBy.name).toBe("Moscow Exchange");
  });

  it("has 150 to 300 issues with unique tickers", () => {
    expect(BONDS.length).toBeGreaterThanOrEqual(150);
    expect(BONDS.length).toBeLessThanOrEqual(300);
    expect(new Set(BONDS.map((b) => b.id)).size).toBe(BONDS.length);
  });

  it("has every kind the screen shows", () => {
    const count = (f: (b: Bond) => boolean) => BONDS.filter(f).length;
    expect(count((b) => b.issuer.kind === "government")).toBeGreaterThan(20);
    for (const kind of ["fixed", "key_rate", "ruonia", "linker"] as const) expect(count((b) => b.coupon.kind === kind), kind).toBeGreaterThan(0);
    expect(count((b) => b.issue.amortization.length > 0)).toBeGreaterThan(5);
    expect(count((b) => b.offer?.kind === "put")).toBeGreaterThan(5);
    expect(count((b) => b.offer?.kind === "call")).toBeGreaterThan(2);
    expect(count((b) => b.subordinated)).toBeGreaterThan(2);
    expect(count((b) => b.qualifiedOnly)).toBeGreaterThan(2);
    // Each issuer's rating has an outlook, mostly stable; the treasury's is.
    for (const outlook of ["stable", "positive", "negative"] as const) expect(count((b) => b.outlook === outlook), outlook).toBeGreaterThan(0);
    expect(count((b) => b.outlook === "stable")).toBeGreaterThan(BONDS.length / 2);
    expect(BONDS.filter((b) => b.issuer.kind === "government").every((b) => b.outlook === "stable")).toBe(true);
  });

  it("every issue derives in the twin at the yield it was priced at, within half a price step", () => {
    for (const b of BONDS) {
      const r = derive_bond(b.issue, MARKET);
      if (!("ok" in r)) throw new Error(`${b.id}: ${r.error}`);
      const dirtyPct = (r.ok.dirtyPrice / b.issue.nominal) * 100;
      const bound = (1.1 * (b.tickPct / 2)) / (dirtyPct * b.duration) + 1e-9;
      expect(Math.abs(r.ok.yieldEvent - b.targetYield), b.id).toBeLessThanOrEqual(bound);
    }
  });

  it("gives an issue's day through the same build: sessions, a tape on the price step and a book", () => {
    type Day = { sessions: { kind: string }[]; prints: [number, number, number, string][]; book: { bids: [number, number][]; asks: [number, number][] } };
    const whole = JSON.parse(dayJson(0)) as Day;
    expect(whole.sessions.map((s) => s.kind)).toEqual(["opening_auction", "morning", "main", "closing_auction", "evening"]);
    expect(whole.prints.length).toBeGreaterThan(10);
    // Prices in units of 0.0001 percent of face, on the government step.
    for (const [, price] of whole.prints) expect(price % 10).toBe(0);
    // The book is empty after the evening session, and full at midday.
    expect(whole.book.bids).toEqual([]);
    const midday = JSON.parse(dayJson(0, 0, 13 * 3_600_000, 5)) as Day;
    expect(midday.book.bids).toHaveLength(5);
    expect(midday.book.asks[0]![0]).toBeGreaterThan(midday.book.bids[0]![0]);
    expect(dayJson(0)).toBe(dayJson(0));
    expect(dayJson(BONDS.length)).toBe("null");
  });

  it("refuses a place the interface has no name for", () => {
    const json = generate().json.replaceAll('"place":"volga"', '"place":"atlantis"');
    expect(() => parseUniverse(json)).toThrow(/unknown issuer/);
  });
});

/** Real names the interface must never write for an issuer of this
 * universe: issuers on the Russian bond market and the government's
 * borrower, in Russian and English. */
const REAL_NAMES = [
  "минфин", "министерство финансов", "ministry of finance", "minfin", "офз", "ofz",
  "сбер", "sber", "втб", "vtb", "газпром", "gazprom", "роснефть", "rosneft", "лукойл", "lukoil", "ржд", "russian railways",
  "ростелеком", "rostelecom", "мтс", "mts", "магнит", "magnit", "сегежа", "segezha", "самолёт", "самолет", "samolet",
  "пик", "pik", "система", "sistema", "норильский никель", "nornickel", "нлмк", "nlmk", "северсталь", "severstal", "ммк", "mmk",
  "евраз", "evraz", "полюс", "polyus", "алроса", "alrosa", "русал", "rusal", "металлоинвест", "metalloinvest", "акрон", "acron",
  "фосагро", "phosagro", "сибур", "sibur", "новатэк", "novatek", "транснефть", "transneft", "русгидро", "rushydro", "россети", "rosseti",
  "аэрофлот", "aeroflot", "озон", "ozon", "яндекс", "yandex", "тинькофф", "tinkoff", "т-банк", "t-bank", "альфа", "alfa",
  "газпромбанк", "gazprombank", "совкомбанк", "sovcombank", "открытие", "otkritie", "псб", "psb", "дом.рф", "dom.rf", "вэб", "veb",
  "европлан", "europlan", "гтлк", "gtlk", "балтийский лизинг", "baltic leasing", "уралсиб", "uralsib", "кубань кредит", "kuban credit",
  "кубаньэнерго", "kubanenergo", "волгателеком", "volgatelecom", "уральская сталь", "ural steel", "акра", "acra", "эксперт ра", "expert ra",
];

describe("names on screen", () => {
  it("no issuer's name, in Russian or English, is or contains a real issuer's name", () => {
    const words = (s: string) => s.toLocaleLowerCase().split(/[^\p{L}\p{N}.\-]+/u);
    for (const lang of ["ru", "en"] as const) {
      const names = new Map<string, string>();
      for (const b of BONDS) {
        const name = issuerName(b, strings[lang]);
        const lower = name.toLocaleLowerCase();
        for (const real of REAL_NAMES) {
          const hit = real.includes(" ") || real.includes(".") ? lower.includes(real) : words(name).includes(real);
          expect(hit, `${lang}: ${name} (${real})`).toBe(false);
        }
        // One name per issuer.
        const code = b.issuer.code;
        expect(names.get(name) ?? code, `${lang}: ${name}`).toBe(code);
        names.set(name, code);
      }
    }
  });

  it("the government group is named as synthetic, and its issuer is not a ministry", () => {
    for (const lang of ["ru", "en"] as const) {
      const t = strings[lang];
      expect(t.chipGov.toLocaleLowerCase()).toMatch(/synthetic|синтетическ/);
      expect(t.tagGov.toLocaleLowerCase()).toMatch(/synthetic|синтетическ/);
      expect(t.govIssuer.toLocaleLowerCase()).toMatch(/synthetic|синтетическ/);
      expect(t.rating.toLocaleLowerCase()).toMatch(/synthetic|синтетическ/);
    }
  });
});
