// For unit tests: the universe the app shows, generated by tyche-market's
// WebAssembly build loaded from the linked package's file, as the worker
// generates it in the browser.
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { SynthMarket, initSync } from "tyche-market";
import { MACRO, SEED } from "./market";
import { parseUniverse, type MacroInputs, type Universe } from "./issues";

const require = createRequire(import.meta.url);
const pkg = dirname(require.resolve("tyche-market/package.json"));
initSync({ module: readFileSync(join(pkg, "tyche_market_bg.wasm")) });

/** The universe's JSON and digest for a seed and inputs. */
export function generate(seed = SEED, inputs: MacroInputs = MACRO): { json: string; digest: string } {
  const m = new SynthMarket(seed, inputs.valuationDate, inputs.keyRatePct, inputs.ruoniaPct, inputs.inflationPct, Float64Array.from(inputs.curve.termsYears), Float64Array.from(inputs.curve.yieldsPct));
  const out = { json: m.universeJson(), digest: m.digest() };
  m.free();
  return out;
}

export const UNIVERSE: Universe = parseUniverse(generate().json);
export const BONDS = UNIVERSE.bonds;

/** tyche-market's own fallback figures. */
export function fallbackInputs(): MacroInputs {
  return (JSON.parse(SynthMarket.fallbackInputs()) as { inputs: MacroInputs }).inputs;
}

/** An issue's day in the synthetic market, as JSON. */
export function dayJson(index: number, day = 0, untilMs = -1, levels = 10): string {
  const m = new SynthMarket(SEED, MACRO.valuationDate, MACRO.keyRatePct, MACRO.ruoniaPct, MACRO.inflationPct, Float64Array.from(MACRO.curve.termsYears), Float64Array.from(MACRO.curve.yieldsPct));
  const out = m.dayJson(index, day, untilMs, levels);
  m.free();
  return out;
}

/** The markets built for the events, one per seed and inputs, kept for
 * the test run. */
const markets = new Map<string, SynthMarket>();

/** A holding's events, as JSON, for a universe of a seed and inputs. */
export function eventsJson(index: number, bonds: number, seed = SEED, inputs: MacroInputs = MACRO): string {
  const key = JSON.stringify([seed, inputs]);
  let m = markets.get(key);
  if (!m) {
    m = new SynthMarket(seed, inputs.valuationDate, inputs.keyRatePct, inputs.ruoniaPct, inputs.inflationPct, Float64Array.from(inputs.curve.termsYears), Float64Array.from(inputs.curve.yieldsPct));
    markets.set(key, m);
  }
  return m.eventsJson(index, bonds);
}
